name: smb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.0=py37_0
  - astor=0.8.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bokeh=2.1.1=py37_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py37h06a4308_0
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=1.2.2=py_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask=2.10.1=py_0
  - dask-core=2.10.1=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.16.0=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fsspec=0.8.3=py_0
  - gast=0.3.2=py_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - google-pasta=0.1.7=py_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py37h989c5e5_3
  - hdf5=1.10.2=hba1933b_1
  - heapdict=1.0.1=py_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.6.1=py37_0
  - importlib_metadata=1.4.0=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.3.0=py37h5ca1d4c_0
  - ipython=7.10.2=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - llvmlite=0.32.1=py37hd408876_0
  - locket=0.2.0=py37_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - more-itertools=8.0.2=py_0
  - msgpack-python=1.0.1=py37hff7bd54_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - notebook=6.0.3=py37_0
  - numba=0.49.1=py37h0573a6f_0
  - numpy=1.17.2=py37haad9e8e_0
  - numpy-base=1.17.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandas=1.2.0=py37ha9443f7_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.2.3=py37_0
  - prometheus_client=0.8.0=py_0
  - prompt_toolkit=3.0.2=py_0
  - protobuf=3.9.2=py37he6710b0_0
  - psutil=5.7.2=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - pybind11=2.4.3=py37hfd86e86_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.15.7=py37h7b6447c_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - python-wget=3.2=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37h7b6447c_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - pyzmq=19.0.1=py37he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - scikit-image=0.16.2=py37h0573a6f_0
  - scikit-learn=0.22=py37hd81dba3_0
  - scipy=1.3.1=py37h7c811a0_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.4.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sortedcontainers=2.3.0=pyhd3eb1b0_0
  - sqlite=3.30.0=h7b6447c_0
  - tbb=2020.0=hfd86e86_0
  - tblib=1.7.0=py_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - traitlets=4.3.3=py37_0
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.2=he6710b0_2
  - zict=2.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - tornado==5.1.1
prefix: /opt/anaconda/envs/smb_env